kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/realm-created: 'false'
  resourceVersion: '3875641'
  name: keycloak
  uid: f7269dd8-4e25-4ba0-8dd0-8edd48e8df60
  creationTimestamp: '2023-09-25T11:23:26Z'
  generation: 2
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-09-25T11:23:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:argocd.argoproj.io/realm-created': {}
          'f:labels':
            .: {}
            'f:application': {}
            'f:template.openshift.io/template-instance-owner': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"a74653f0-36af-4354-b9d0-efaa7d8f133c"}': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:deploymentConfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:recreateParams':
              .: {}
              'f:timeoutSeconds': {}
            'f:resources':
              'f:limits':
                .: {}
                'f:cpu': {}
                'f:memory': {}
              'f:requests':
                .: {}
                'f:cpu': {}
                'f:memory': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:application': {}
                'f:deploymentConfig': {}
              'f:name': {}
            'f:spec':
              'f:volumes':
                .: {}
                'k:{"name":"service-ca"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"sso-probe-netrc-volume"}':
                  .: {}
                  'f:emptyDir':
                    .: {}
                    'f:medium': {}
                  'f:name': {}
                'k:{"name":"sso-x509-https-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
              'f:containers':
                .: {}
                'k:{"name":"keycloak"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/etc/x509/https"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
                    'k:{"mountPath":"/mnt/rh-sso"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/var/run/configmaps/service-ca"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"DB_TX_ISOLATION"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_HOSTNAME"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"DB_MAX_POOL_SIZE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"OPENSHIFT_DNS_PING_SERVICE_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"X509_CA_BUNDLE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_REALM"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_SERVICE_USERNAME"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"OPENSHIFT_DNS_PING_SERVICE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_SERVICE_PASSWORD"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"DB_MIN_POOL_SIZE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_ADMIN_USERNAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_ADMIN_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8443,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8778,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8888,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              .: {}
              'f:schedulerName': {}
              'f:nodeSelector': {}
              'f:terminationGracePeriodSeconds': {}
              'f:securityContext': {}
          'f:triggers': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-09-25T11:26:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"keycloak"}':
                  'f:readinessProbe':
                    'f:initialDelaySeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-09-25T11:28:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: openshift-gitops
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      name: openshift-gitops
      uid: a74653f0-36af-4354-b9d0-efaa7d8f133c
      controller: true
  labels:
    application: keycloak
    template.openshift.io/template-instance-owner: b851dcc2-91d5-4182-b7cd-af189f718b5e
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: keycloak
  template:
    metadata:
      name: keycloak
      creationTimestamp: null
      labels:
        application: keycloak
        deploymentConfig: keycloak
    spec:
      volumes:
        - name: sso-x509-https-volume
          secret:
            secretName: sso-x509-https-secret
            defaultMode: 420
        - name: service-ca
          configMap:
            name: keycloak-service-ca
            defaultMode: 420
        - name: sso-probe-netrc-volume
          emptyDir:
            medium: Memory
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 120
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: keycloak
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 120
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SSO_HOSTNAME
            - name: DB_MIN_POOL_SIZE
            - name: DB_MAX_POOL_SIZE
            - name: DB_TX_ISOLATION
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: keycloak-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: X509_CA_BUNDLE
              value: >-
                /var/run/configmaps/service-ca/service-ca.crt
                /var/run/secrets/kubernetes.io/serviceaccount/*.crt
            - name: SSO_ADMIN_USERNAME
              value: TPByvKHa
            - name: SSO_ADMIN_PASSWORD
              value: NBcfCIsN
            - name: SSO_REALM
            - name: SSO_SERVICE_USERNAME
            - name: SSO_SERVICE_PASSWORD
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ping
              containerPort: 8888
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: sso-x509-https-volume
              readOnly: true
              mountPath: /etc/x509/https
            - name: service-ca
              readOnly: true
              mountPath: /var/run/configmaps/service-ca
            - name: sso-probe-netrc-volume
              mountPath: /mnt/rh-sso
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:ec9f60018694dcc5d431ba47d5536b761b71cb3f66684978fe6bb74c157679ac
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 2
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 0
  unavailableReplicas: 1
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2023-09-25T11:28:19Z'
      lastTransitionTime: '2023-09-25T11:28:19Z'
      message: Deployment config does not have minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-09-25T11:28:22Z'
      lastTransitionTime: '2023-09-25T11:26:34Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "keycloak-2" successfully rolled out
