kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/realm-created: 'false'
  resourceVersion: '153741'
  name: keycloak
  uid: e96cb3a7-60b2-48dd-8e48-81f1d87dd016
  creationTimestamp: '2021-08-24T07:21:15Z'
  generation: 1
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2021-08-24T07:21:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:argocd.argoproj.io/realm-created': {}
          'f:labels':
            .: {}
            'f:application': {}
            'f:template.openshift.io/template-instance-owner': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"37670de4-955b-4e32-8999-8a834daf11cd"}':
              .: {}
              'f:apiVersion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:deploymentConfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:recreateParams':
              .: {}
              'f:timeoutSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:application': {}
                'f:deploymentConfig': {}
              'f:name': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"keycloak"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/etc/x509/https"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
                    'k:{"mountPath":"/var/run/configmaps/service-ca"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    'k:{"name":"DB_TX_ISOLATION"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_HOSTNAME"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"DB_MAX_POOL_SIZE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"OPENSHIFT_DNS_PING_SERVICE_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"X509_CA_BUNDLE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_REALM"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_SERVICE_USERNAME"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"OPENSHIFT_DNS_PING_SERVICE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_SERVICE_PASSWORD"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"DB_MIN_POOL_SIZE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"SSO_ADMIN_USERNAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SSO_ADMIN_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8443,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8778,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8888,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"service-ca"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"sso-x509-https-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
          'f:triggers': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:latestVersion': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
  namespace: openshift-gitops
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      name: openshift-gitops
      uid: 37670de4-955b-4e32-8999-8a834daf11cd
      controller: true
  labels:
    application: keycloak
    template.openshift.io/template-instance-owner: b6507461-1fe9-4499-a5cb-c39cc593dcc0
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: keycloak
  template:
    metadata:
      name: keycloak
      creationTimestamp: null
      labels:
        application: keycloak
        deploymentConfig: keycloak
    spec:
      volumes:
        - name: sso-x509-https-volume
          secret:
            secretName: sso-x509-https-secret
            defaultMode: 420
        - name: service-ca
          configMap:
            name: keycloak-service-ca
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: keycloak
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SSO_HOSTNAME
            - name: DB_MIN_POOL_SIZE
            - name: DB_MAX_POOL_SIZE
            - name: DB_TX_ISOLATION
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: keycloak-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: X509_CA_BUNDLE
              value: >-
                /var/run/configmaps/service-ca/service-ca.crt
                /var/run/secrets/kubernetes.io/serviceaccount/*.crt
            - name: SSO_ADMIN_USERNAME
              value: eLa6tBoB
            - name: SSO_ADMIN_PASSWORD
              value: c8wkXjDM
            - name: SSO_REALM
            - name: SSO_SERVICE_USERNAME
            - name: SSO_SERVICE_PASSWORD
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ping
              containerPort: 8888
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: sso-x509-https-volume
              readOnly: true
              mountPath: /etc/x509/https
            - name: service-ca
              readOnly: true
              mountPath: /var/run/configmaps/service-ca
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/rh-sso-7/sso74-openshift-rhel8@sha256:39d752173fc97c29373cd44477b48bcb078531def0a897ee81a60e8d1d0212cc
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  latestVersion: 1
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 0
  unavailableReplicas: 1
  details:
    message: config change
    causes:
      - type: ConfigChange
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2021-08-24T07:21:15Z'
      lastTransitionTime: '2021-08-24T07:21:15Z'
      message: Deployment config does not have minimum availability.
    - type: Progressing
      status: Unknown
      lastUpdateTime: '2021-08-24T07:21:15Z'
      lastTransitionTime: '2021-08-24T07:21:15Z'
      message: >-
        replication controller "keycloak-1" is waiting for pod
        "keycloak-1-deploy" to run
